import type { DocLang } from "./types";

/** Words printed inside the PDF/preview, in the document's own language. */
export const docLabels = {
  it: {
    quote: "PREVENTIVO",
    number: "Numero",
    date: "Data",
    validUntil: "Valido fino al",
    subject: "Oggetto",
    from: "Da",
    to: "Spett.le",
    vat: "P. IVA",
    taxCode: "C.F.",
    pec: "PEC",
    sdi: "SDI",
    phone: "Tel.",
    email: "Email",
    description: "Descrizione",
    qty: "Q.tà",
    unitPrice: "Prezzo unit.",
    discount: "Sconto",
    vatRate: "IVA",
    amount: "Importo",
    subtotal: "Subtotale",
    lineDiscounts: "Sconti di riga",
    globalDiscount: "Sconto",
    net: "Imponibile",
    rivalsa: "Rivalsa INPS",
    taxable: "Totale imponibile",
    vatOn: "IVA",
    bollo: "Imposta di bollo",
    total: "Totale",
    ritenuta: "Ritenuta d'acconto",
    netPayable: "Netto a pagare",
    deposit: "Acconto alla conferma",
    notes: "Note",
    paymentTerms: "Condizioni di pagamento",
    acceptance: "Per accettazione",
    signature: "Firma e timbro del cliente",
    forfettarioNote:
      "Operazione senza applicazione dell'IVA ai sensi dell'art. 1, commi da 54 a 89, L. 190/2014 (regime forfettario). Non soggetta a ritenuta d'acconto ai sensi dell'art. 1, comma 67, L. 190/2014.",
    bolloNote: "Imposta di bollo assolta sull'originale (€ 2,00) per importi esenti IVA superiori a € 77,47.",
    exemptNote: "Operazione esente / non soggetta a IVA.",
    preview: "ANTEPRIMA",
    page: "Pagina",
    of: "di",
    generatedWith: "Preventivo generato con Preventivo Lampo",
  },
  en: {
    quote: "QUOTE",
    number: "Number",
    date: "Date",
    validUntil: "Valid until",
    subject: "Subject",
    from: "From",
    to: "To",
    vat: "VAT",
    taxCode: "Tax code",
    pec: "PEC",
    sdi: "SDI",
    phone: "Phone",
    email: "Email",
    description: "Description",
    qty: "Qty",
    unitPrice: "Unit price",
    discount: "Discount",
    vatRate: "VAT",
    amount: "Amount",
    subtotal: "Subtotal",
    lineDiscounts: "Line discounts",
    globalDiscount: "Discount",
    net: "Net amount",
    rivalsa: "INPS surcharge",
    taxable: "Taxable amount",
    vatOn: "VAT",
    bollo: "Stamp duty",
    total: "Total",
    ritenuta: "Withholding tax",
    netPayable: "Net payable",
    deposit: "Deposit on acceptance",
    notes: "Notes",
    paymentTerms: "Payment terms",
    acceptance: "Accepted by",
    signature: "Client signature and stamp",
    forfettarioNote:
      "VAT not applied pursuant to art. 1, par. 54–89, Italian Law 190/2014 (flat-rate scheme). Not subject to withholding tax pursuant to art. 1, par. 67, Law 190/2014.",
    bolloNote: "Stamp duty (€ 2.00) paid on the original for VAT-exempt amounts above € 77.47.",
    exemptNote: "VAT exempt / out of scope.",
    preview: "PREVIEW",
    page: "Page",
    of: "of",
    generatedWith: "Quote generated with Preventivo Lampo",
  },
} as const satisfies Record<DocLang, Record<string, string>>;

export type DocLabels = Record<keyof (typeof docLabels)["it"], string>;

export function labelsFor(lang: DocLang): DocLabels {
  return (docLabels[lang] ?? docLabels.it) as DocLabels;
}
